### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by kmaslowiec** [kmaslowiec/ask-crossfit#7]
- [x] First test in rep and viewModel https://github.com/kmaslowiec/ask-crossfit/pull/8
- [x] testing loading in repo #12 
- [x] ViewModel test if addWrongAnswerToStats is called #13 
- [x] ViewModel test if is called and gives data, loading state and how it acts on faiure #26
- [ ] Test StatRepo [possible solution](https://medium.com/androiddevelopers/datastore-and-testing-edf7ae8df3d8)
